name: flutter_map_training
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.10.1

dependencies:
  flutter:
    sdk: flutter
  flutter_map: ^8.2.2
  geocoding: ^4.0.0
  geodesy: ^0.10.2
  geolocator: ^14.0.2
  google_maps_flutter: ^2.14.0
  http: ^1.6.0
  latlong2: ^0.9.1
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
